import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <div className="flex h-screen">
          <main className="h-full m-auto container w-full lg:pr-20  md:pt-20 md:pr-20 md:pb-20 md:pl-40 p-5 py-10 pl-20">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
